### ISSUE TITLE
submit scrapy-kafka to PyPI?

### ISSUE THREAD

**Issue by alexwoolford** [dfdeshom/scrapy-kafka#2]
Thanks for writing scrapy-kafka. It's been really useful.

Have you thought about submitting this to PyPI? It'd be easier to deploy via pip/ansible (or whatever) if it were part of the Python Package Index.

**Comment by dfdeshom** [comment]
Hi,
Glad to hear this has been useful to you! I plan to add this to pypi soon, give until the end of the week. Thanks!

**Comment by alexwoolford** [comment]
Thanks so much, Didier. That's excellent. Very much appreciated.

**Comment by dfdeshom** [comment]
@alexwoolford it's on pypi now: https://pypi.python.org/pypi/scrapy-kafka .
