### ISSUE TITLE
Please create a better example with zookeeper and kafka both

### ISSUE THREAD

**Issue by avinash-mishra** [dfdeshom/scrapy-kafka#3]
I think example mentioned is not enough to configure the project. It would be great if someone can update example directory to make things more clear. 
I am struggling how to configure zookeeper and kafka inside settings.py

**Comment by dfdeshom** [comment]
Thanks for the suggestion. I've made the settings more explicit here: https://github.com/dfdeshom/scrapy-kafka/blob/master/example/example/settings.py#L20-L22 . 

There is no setting to expose zookeeper as kafka-python doesn't expose that (we use kafka-python to connect to kafka): http://kafka-python.readthedocs.io/en/master/apidoc/KafkaConsumer.html
